# @package _group_
type: LSTM
num_layers: 2 # Number of LSTM layers in the model.
bidirectional: False # Whether to use Bidirectional LSTM.
hidden_units: 50 # Number of hidden units/LSTM cells per layer.
dropout_rate: 0.0 # Dropout probability, applied to the dense layer after the LSTM.
