# @package _group_
train: True # Boolean that describes whether we are training or testing using a trained model.
epochs: 20
batch_size: 256 # 512 in paper
learning_rate: 3e-3
optimiser: Adam
loss_fn: MSE
test_metric: NSE
checkpoint_freq: 1 # How many epochs we should train for before checkpointing the model.
val_interval: 0.25 # If this is a float, it is the proportion of the training set that should go between validation epochs.
# If this is an int, it denotes the number of batches in between validation epochs.
log_steps: 50 # How many gradient updates between each log point.
fine_tune: False # Whether or not we are fine-tuning on Shipston data.
date_range: [] # Custom date range for the train dataset, as a list of two strings.
mc_dropout: False # Whether or not to use MC Dropout to get output uncertainty.
mc_dropout_iters: 20 # Number of forward passes to use with MC dropout to get uncertainty.
